# Python

In [15]:
import numpy as np
import pandas as pd

### Exercise 1.1: Data Structures and Filtering
**Task:** 1. Create a list of dictionaries where each dictionary represents a student with `name` and `score`.
2. Use a `for` loop or the `filter()` function to extract only the students who scored 60 or above.
3. Print the names of the passing students.

In [16]:
# 1. Define your list of dictionaries here
students = [
    {"name": "Ali", "score": 85},
    {"name": "Omar", "score": 45},
    {"name": "Ayesha", "score": 78},
    {"name": "Bilal", "score": 55}
]

# 2. Write a function to check if a student passed (score >= 60)
def check_pass(student):
    # YOUR CODE HERE: Return True if score >= 60, else False
    return (student['score'] >= 60)

# 3. Use filter() or a loop to get passed students
# YOUR CODE HERE
passed_student = []
for student in students:
    if check_pass(student):
        passed_student.append(student['name'])
# 4. Print the result
# YOUR CODE HERE
passed_student

['Ali', 'Ayesha']

### Exercise 2.1: Flexible Functions
**Task:**
1. Write a function called `calculate_total` that takes an arbitrary number of numeric arguments using `*args` and returns their sum.
2. Create a lambda function that squares a given number. Use the `map()` function to apply this lambda to a list of numbers.

In [27]:
# 1. Define calculate_total using *args
def calculate_total(*args):
    # YOUR CODE HERE: Sum the arguments and return the result
    sum = 0
    for i in args:
        sum+=i
    return sum

# Test your function
print("Total Sum:", calculate_total(10, 20, 30, 40.5))

# 2. Lambda and Map
numbers = [2, 4, 6, 8]

# YOUR CODE HERE: Create a lambda function to square a number
# square_func = lambda ...
square_func = lambda x : x**2 

# YOUR CODE HERE: Use map() to apply the lambda to the 'numbers' list
# squared_numbers = map(...)
print(map( square_func ,numbers))
# Print the list of squared numbers
# print(list(squared_numbers))

Total Sum: 100.5


In [38]:
f = []
for _ in range(3):
    f.append(lambda x: x+_)
    _+=1
_+=1
print([i(10) for i in f])

[14, 14, 14]


### Exercise 3.1: The `__name__` Variable
**Question:** Imagine you have a file named `robot_control.py`. Inside it, you have a function `start_motor()` and an `if __name__ == "__main__":` block. If you import `robot_control` into another file, will the code inside the `if` block run?

**Task:** Write a small snippet below to demonstrate how you would structure `robot_control.py` so that it only prints "System Armed!" when run directly, but NOT when imported.

In [18]:
def start_motor():
    print("Motor started.")

# YOUR CODE HERE: Write the if __name__ condition
# if ...
    # print("System Armed!")
if __name__ == '__main__':
    start_motor()

Motor started.


### Exercise 4.1: NumPy Arrays and Slicing
**Task:**
1. Import numpy.
2. Create a 3x3 array filled with zeros.
3. Change the center element of this array to 9.
4. Create a 1D array of numbers from 1 to 4. Reshape it into a 2x2 matrix.

In [42]:
# 1. Import numpy
# YOUR CODE HERE
import numpy as np
# 2. Create a 3x3 array of zeros
# z_matrix = ...
# print("Original Zeros:\\n", z_matrix)
z_matrix = np.zeros((3,3))
print("Original Zeros:\n", z_matrix)
# 
# 3. Change the center element (row index 1, col index 1) to 9
# YOUR CODE HERE
# print("Modified Matrix:\\n", z_matrix)
z_matrix[1,1] = 9
print("Modified Matrix:\n", z_matrix)
# 
# 4. Create an array [1, 2, 3, 4] and reshape it to 2x2
arr = np.array([1,2,3,4])
reshaped_arr = arr.reshape((2,2))
print("Reshaped Array:\n", reshaped_arr)

Original Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Modified Matrix:
 [[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
Reshaped Array:
 [[1 2]
 [3 4]]


### Exercise 4.2: Element-wise Math and Statistics
**Task:**
Using the `reshaped_arr` from the previous step:
1. Multiply the entire array by 10.
2. Find the maximum value in the array.
3. Find the sum of the array along axis 0 (columns).

In [46]:
# 1. Multiply by 10
multiplied = arr * 10
print("Multiplied:\n", multiplied)

# 2. Find the maximum value
max_val = arr.max()
print("Max Value:", max_val)

# 3. Sum along axis 0
sum_cols = arr.sum()
print("Sum of columns:", sum_cols)

Multiplied:
 [10 20 30 40]
Max Value: 4
Sum of columns: 10


### Exercise 5.1: Loading Data with Pandas
**Task:**
1. Import the pandas library.
2. Write the code to read a CSV file named `dataset.csv`.
3. Instead of printing the `tail` (bottom 5 rows) like in your class script, write the command to print the `head` (top 5 rows) of the dataset.

In [47]:
# 1. Import pandas
# YOUR CODE HERE
import pandas as pd
# 2. Load the CSV (Assume the file exists in your directory)
# df = ...
df =  read_csv("file.txt")
# 3. Print the top 5 rows
# YOUR CODE HERE
df.head(5)

NameError: name 'read_csv' is not defined

making a txt file with the below content.

In [1]:
%%file file.txt
1,a
2,b
3,c

Writing file.txt
